version: '3.8'

services:
  face_recognition:
    build:
      context: ./face_recognition
      dockerfile: Dockerfile
    container_name: safetywatch_face_api
    ports:
      - "8000:8000"
    volumes:
      - ./face_recognition:/app
      - /workspace:/workspace # Runpod persistent storage
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LARAVEL_API_URL=${LARAVEL_API_URL:-https://3.124.186.191.nip.io}
      - LARAVEL_API_TOKEN=${LARAVEL_API_TOKEN:-120|5KEPWG0M5jCgkK8kr8kcMyi0l896vv1gXEGDChTo6baa0b50}
      - CAMERA_API_KEY=${CAMERA_API_KEY:-secret}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  violence_detection:
    build:
      context: ./violence_detection
      dockerfile: Dockerfile
    container_name: safetywatch_violence_api
    ports:
      - "8001:8001"
    volumes:
      - ./violence_detection:/app
      - /workspace:/workspace # Runpod persistent storage
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LARAVEL_API_URL=${LARAVEL_API_URL:-https://3.124.186.191.nip.io}
      - CAMERA_API_KEY=${CAMERA_API_KEY:-secret}
    command: ["python", "edge_worker.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
