databases:
  - name: safetywatch-db
    plan: free
    databaseName: safetywatch_db
    region: frankfurt

services:
  - type: web
    name: safetywatch-api
    plan: free
    region: frankfurt
    rootDir: backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: SafetyWatch
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://safetywatch-api.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: safetywatch-db
          property: connectionString
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array
      - key: QUEUE_CONNECTION
        value: sync
